kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-{{ .Values.public.componentName }}
  labels:
    component: {{ .Values.public.componentName }}
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      component: {{ .Values.public.componentName }}
      release: {{ .Release.Name }}
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        component: {{ .Values.public.componentName }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.public.componentName }}
          resources:
{{ toYaml .Values.public.resources | indent 12 }}
          image: {{ .Values.images.public.name }}:{{ .Values.images.public.tag }}
          imagePullPolicy: {{ .Values.public.imagePullPolicy }}
          ports:
            - name: {{ .Values.public.service.portName }}
              containerPort: {{ .Values.public.service.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 10
          startupProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 10
          volumeMounts:
            - name: snowplow
              mountPath: /usr/share/caddy/_scripts
              readOnly: true
      volumes:
        - name: snowplow
          configMap:
            name: snowplow
            defaultMode: 420